USE [Zimmer_Prod]
GO
/****** Object:  StoredProcedure [dbo].[sp_bde_item_fetch]    Script Date: 03.12.2024 16:57:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[sp_bde_item_fetch]
	@id VARCHAR(MAX)
AS
BEGIN
	SET NOCOUNT ON;
	SELECT 
		CONCAT('A', A.NUMMER) AS ITM_IDNR,
		A.BEZ1 AS ITM_VAR1,
		A.BEZ2 AS ITM_VAR2,
		A.BEZ3 AS ITM_VAR3,
		A.WERKSTOFF AS ITM_MATERIAL,
		A.NORM as ITM_STANDARD,
		A.GRUNDEHT as ITM_UNIT,
		UPPER(E.BEZ) AS ITM_UNIT_DESC,
		A.SNR_ABGANG AS ITM_SERIALREQUIRED
	FROM Artikel AS A
					LEFT JOIN
						EINHEITEN AS E ON E.MANDANT = 1 AND E.NUMMER = A.GRUNDEHT
	WHERE CONCAT('A', A.NUMMER) = @id AND A.MANDANT = 1 
	UNION ALL
	SELECT 
		CONCAT('T', T.NUMMER) AS ITM_IDNR, 
		T.BEZ1 AS ITM_VAR1,
		T.BEZ2 AS ITM_VAR2,
		T.BEZ3 AS ITM_VAR3,
		'' AS ITM_MATERIAL,
		'' as ITM_STANDARD,
		'' as ITM_UNIT,
		'' AS ITM_UNIT_DESC,
		'' AS ITM_SERIALREQUIRED
	FROM Teile AS T
	WHERE CONCAT('T', T.NUMMER) = @id;
END